version: '3'
services:
  girandole:
    build: .
    ports:
    - ${GIRANDOLE_PORT}:8080
    volumes:
    - ./girandole:/opt/girandole  # Remove in production.
    - ${GIRANDOLE_MUSIC_DIR}:${GIRANDOLE_MUSIC_DIR}
    - ${GIRANDOLE_MUSIC_DATA}:${GIRANDOLE_MUSIC_DATA}
    - ${GIRANDOLE_BEETS_DB}:/etc/beets/library.db
    - ${GIRANDOLE_BEETS_CONFIG}:/etc/beets/config.yaml
    - ${GIRANDOLE_WLG_DIR}:/root/.whatlastgenre
    entrypoint: uvicorn --host 0.0.0.0 --port 8080 girandole.main:app --reload
